### ISSUE TITLE
Litigant entered data parameters

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#55]
Household size field should allow only 1-15
Total income should allow only $0-$900,000
Monthly costs fields should allow only $0-$10,000 for each; blank is ok - not mandatory to enter $0 if no expense in a certain category, if possible

**Comment by jmadans** [comment]
Done. I don't think we should make the monthly expense fields not-required because this page is so long and people are likely to miss things accidentally. 

I've added a prompt for users to enter 0 if they don't have that expense. We're also working on an update so we can customize the error response. So instead of saying "You must enter your expense" we can say "If you don't have this expense enter zero".
