### ISSUE TITLE
upload file name

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#61]
alphanumeric characters of the uploaded benefits card file (Akbar provided a screenshot in an email 1/25) instead of the actual file name that was uploaded (e,g, Benefits Card.jpg, or Proof.tiff)

**Comment by jmadans** [comment]
Instead of using the user generated file name (which could be anything/probably not helpful), how about we programmatically rename each attachment to match the title of the page? Hear me out. 

In the new UI we add a new page for each benefit checked by the user which means the title for each page is "Proof of [benefit name]". So, if we have the attachment match the page title it would just be "Proof of Calfresh". 

This would make the attachment names more standardized and easily intelligible for court staff within the judicial module.

**Comment by rdeshpande** [comment]
Hey @jmadans - just want to confirm we want to do the following format:

<original filename>_ProofOf<whatever>.<extension>

Or do we want to just use the old filename?

**Comment by jmadans** [comment]
Opposite direction. We just want it to be "Proof of [whatever].jpg"

**Comment by rdeshpande** [comment]
Complete on PROD and UAT.
